### ISSUE TITLE
Optical Duplicates -- MarkDuplicates

### ISSUE THREAD

**Issue by chrishusted** [jmkidd/dogmap#1]
Hi there,

I'd like to inquire about your MarkDuplicates step.  I've seen that GATK pipelines tend to include an optical duplicate step.  I'm just curious if there is a reason why this wasn't included, and if so, what is the reasoning behind that?  Thank you so much!  I really appreciate it.

Best,
Chris

**Comment by jmkidd** [comment]
Hi!  GATK MarkDuplicates includes optical duplicates by default, so they are found too.  However, this can only be done when the read cluster location info is in the readname, and this may not always be present (for example, in some read files from SRA).
